### ISSUE TITLE
Rapid fire and a little more.

### ISSUE THREAD

**Issue by QwakeIsBest** [HackerHansen/1v1.YEET-v2#16]
Dear HackerHansen, It has come to my attention that for some strange reason you hack clients rapid fire does not seem to work, I have tried to use every browser, brave, chrome, firefox. and the only one it works on is in firefox, it would be kind of you if you where to make it work for compatablity mode, speaking of, could you make this mode have a few more features, this may inclued glide, hide buildings, ect, thank you , kind regard, -Qwake

**Comment by HackerHansen** [comment]
I just checked and rapid fire still works for me. I'm not sure why it doesn't work for you. 

Unfortunately, I don't plan on adding other features to compatibility mode because those features are already available in Firefox, and compatibility mode was pretty much only supposed to have basic features for people who don't want to install Firefox.
