### ISSUE TITLE
Air Jump and Zombies

### ISSUE THREAD

**Issue by QwakeIsBest** [HackerHansen/1v1.YEET-v2#18]
Dear hacker hansen, my friend has requested for you to add a feature where when sing air jump. when you stop jumping, you wouldn't fall. unlike you would just stand there, floating/hover and you would press shift to either fall down or move down slowly; your choice.

could you maybe add a feature off invisible buildings that you can see but others cannot + could you make zombies not have godmode when  you have it on

**Comment by HackerHansen** [comment]
The first feature you suggested is basically flight. I might add it later, but it would be a pain to fix so idk. 

Invisible buildings already only show for you (unless you're hosting a game). 

I don't plan on making zombies not invincible for god mode because that would likely require additional memory allocation and would probably take way longer to fix than regular god mode. Thanks for the suggestions, though.
